//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Datasets", Namespace="http://schemas.datacontract.org/2004/07/L2")]
    [System.SerializableAttribute()]
    public partial class Datasets : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet HoldingsDataSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet IndustryDataSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet MasterDataSetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet HoldingsDataSet {
            get {
                return this.HoldingsDataSetField;
            }
            set {
                if ((object.ReferenceEquals(this.HoldingsDataSetField, value) != true)) {
                    this.HoldingsDataSetField = value;
                    this.RaisePropertyChanged("HoldingsDataSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet IndustryDataSet {
            get {
                return this.IndustryDataSetField;
            }
            set {
                if ((object.ReferenceEquals(this.IndustryDataSetField, value) != true)) {
                    this.IndustryDataSetField = value;
                    this.RaisePropertyChanged("IndustryDataSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet MasterDataSet {
            get {
                return this.MasterDataSetField;
            }
            set {
                if ((object.ReferenceEquals(this.MasterDataSetField, value) != true)) {
                    this.MasterDataSetField = value;
                    this.RaisePropertyChanged("MasterDataSet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Save", ReplyAction="http://tempuri.org/IService/SaveResponse")]
        void Save(Client.ServiceReference1.Datasets datasets);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Save", ReplyAction="http://tempuri.org/IService/SaveResponse")]
        System.Threading.Tasks.Task SaveAsync(Client.ServiceReference1.Datasets datasets);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDatasets", ReplyAction="http://tempuri.org/IService/GetDatasetsResponse")]
        Client.ServiceReference1.Datasets GetDatasets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDatasets", ReplyAction="http://tempuri.org/IService/GetDatasetsResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference1.Datasets> GetDatasetsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Client.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Client.ServiceReference1.IService>, Client.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Save(Client.ServiceReference1.Datasets datasets) {
            base.Channel.Save(datasets);
        }
        
        public System.Threading.Tasks.Task SaveAsync(Client.ServiceReference1.Datasets datasets) {
            return base.Channel.SaveAsync(datasets);
        }
        
        public Client.ServiceReference1.Datasets GetDatasets() {
            return base.Channel.GetDatasets();
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.Datasets> GetDatasetsAsync() {
            return base.Channel.GetDatasetsAsync();
        }
    }
}
